# Generated by Django 3.0.3 on 2020-07-19 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduletable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('faculty', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('fee', models.IntegerField()),
                ('duration', models.TimeField()),
            ],
        ),
    ]
